version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      core-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
      day: monday
    groups:
      site-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      workflow-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
