import { ZeroGateError } from "./errors.js";
import type { ActionState, TransactionState } from "./types.js";

const transactionTransitions: Readonly<Record<TransactionState, readonly TransactionState[]>> = {
  DRAFT: ["PREFLIGHTING", "ABORTED", "EXPIRED"],
  PREFLIGHTING: ["PREFLIGHT_FAILED", "READY", "ABORTED", "EXPIRED"],
  PREFLIGHT_FAILED: [],
  READY: ["AWAITING_APPROVAL", "COMMIT_REQUESTED", "ABORTED", "EXPIRED"],
  AWAITING_APPROVAL: ["APPROVAL_DENIED", "COMMIT_REQUESTED", "ABORTED", "EXPIRED"],
  APPROVAL_DENIED: [],
  COMMIT_REQUESTED: ["COMMITTING", "ABORTED", "EXPIRED"],
  COMMITTING: ["VERIFYING", "FAILURE_DETECTED", "RECONCILING"],
  VERIFYING: ["VERIFIED_COMMITTED", "FAILURE_DETECTED", "RECONCILING"],
  RELEASING: ["VERIFIED_COMMITTED", "FAILURE_DETECTED", "RECONCILING"],
  VERIFIED_COMMITTED: [],
  FAILURE_DETECTED: ["RECONCILING", "COMPENSATING", "MANUAL_RECOVERY_REQUIRED"],
  RECONCILING: ["VERIFYING", "FAILURE_DETECTED", "COMPENSATING", "MANUAL_RECOVERY_REQUIRED"],
  COMPENSATING: ["VERIFYING_RECOVERY", "PARTIALLY_COMPENSATED", "MANUAL_RECOVERY_REQUIRED"],
  VERIFYING_RECOVERY: ["VERIFIED_COMPENSATED", "PARTIALLY_COMPENSATED", "MANUAL_RECOVERY_REQUIRED"],
  VERIFIED_COMPENSATED: [],
  PARTIALLY_COMPENSATED: ["MANUAL_RECOVERY_REQUIRED"],
  MANUAL_RECOVERY_REQUIRED: [],
  ABORTED: [],
  EXPIRED: []
};

const actionTransitions: Readonly<Record<ActionState, readonly ActionState[]>> = {
  PROPOSED: ["PREFLIGHTING", "CANCELLED"],
  PREFLIGHTING: ["PREFLIGHT_REJECTED", "PREFLIGHTED", "CANCELLED"],
  PREFLIGHT_REJECTED: [],
  PREFLIGHTED: ["AWAITING_APPROVAL", "ADMITTED", "CANCELLED"],
  AWAITING_APPROVAL: ["ADMITTED", "CANCELLED"],
  ADMITTED: ["SCHEDULED", "CANCELLED"],
  SCHEDULED: ["DISPATCHING", "CANCELLED"],
  DISPATCHING: ["OUTCOME_UNKNOWN", "PROVIDER_REJECTED", "REPORTED_SUCCEEDED"],
  OUTCOME_UNKNOWN: ["RECONCILING", "COMPENSATION_RECONCILING"],
  RECONCILING: ["REPORTED_SUCCEEDED", "PROVIDER_REJECTED", "OUTCOME_UNKNOWN", "VERIFICATION_FAILED"],
  PROVIDER_REJECTED: [],
  REPORTED_SUCCEEDED: ["VERIFYING"],
  VERIFYING: ["VERIFIED_SUCCEEDED", "VERIFICATION_FAILED", "DRIFTED"],
  VERIFIED_SUCCEEDED: ["COMPENSATION_PLANNED", "WITHHELD", "RELEASING"],
  VERIFICATION_FAILED: ["COMPENSATION_PLANNED", "COMPENSATION_BLOCKED"],
  DRIFTED: ["COMPENSATION_BLOCKED", "CANCELLED"],
  COMPENSATION_PLANNED: ["COMPENSATING", "COMPENSATION_BLOCKED"],
  COMPENSATING: ["COMPENSATION_UNKNOWN", "COMPENSATION_REPORTED_SUCCEEDED", "COMPENSATION_FAILED"],
  COMPENSATION_UNKNOWN: ["COMPENSATION_RECONCILING"],
  COMPENSATION_RECONCILING: [
    "COMPENSATION_REPORTED_SUCCEEDED",
    "COMPENSATION_FAILED",
    "COMPENSATION_BLOCKED"
  ],
  COMPENSATION_REPORTED_SUCCEEDED: ["COMPENSATION_VERIFYING"],
  COMPENSATION_VERIFYING: ["VERIFIED_COMPENSATED", "COMPENSATION_FAILED"],
  VERIFIED_COMPENSATED: [],
  COMPENSATION_BLOCKED: [],
  COMPENSATION_FAILED: [],
  WITHHELD: ["RELEASING", "CANCELLED"],
  RELEASING: ["VERIFIED_RELEASED", "OUTCOME_UNKNOWN"],
  VERIFIED_RELEASED: [],
  CANCELLED: []
};

export function assertTransactionTransition(from: TransactionState, to: TransactionState): void {
  if (!transactionTransitions[from].includes(to)) {
    throw new ZeroGateError(
      "INVALID_STATE_TRANSITION",
      `Invalid transaction transition: ${from} -> ${to}`,
      false,
      { from, to }
    );
  }
}

export function assertActionTransition(from: ActionState, to: ActionState): void {
  if (!actionTransitions[from].includes(to)) {
    throw new ZeroGateError(
      "INVALID_STATE_TRANSITION",
      `Invalid action transition: ${from} -> ${to}`,
      false,
      { from, to }
    );
  }
}
